### ISSUE TITLE
 RainDropsCaptcha may return the same code multiple times

### ISSUE THREAD

**Issue by Korkman** [librecaptcha/lc-core#140]
Version 1.1.

The RainDropsCaptcha will return the same image multiple times (but with different ids) when requested with `medium` difficulty level. On `easy` difficulty, the bug is not triggered. FilterChallenge does not have this bug.

Edit: it seems to happen after prolonged use of any difficulty level, it is not fixed with `easy`. Changed issue title accordingly.

**Comment by hrj** [comment]
I did a quick test with the master branch and couldn't reproduce this. Will check it again tomorrow with v1.1

In the meanwhile, can you try it on the master branch? Assuming sbt is installed, the command `sbt run` should be enough to start the server.

Also, please share the config file that you have.

**Comment by hrj** [comment]
@Korkman I tried with 1.1 in a fresh directory and the auto-generated config file. I am not able to repro this problem.

Apart from the config file, please share more details of how you observed this bug. Were you using the demo app at `localhost:8888/demo/index.html` ? Did you attempt solving the Captchas when presented or just fetched a new one. (For the record I did the latter, only fetched new ones without solving).

**Comment by Korkman** [comment]
@hrj I was using a PHP curl client, not solving the captchas. But the same effect can be seen with the Demo. Today I noticed the bug appear again, this time the other way around: `easy` would create duplicates, `medium` not. So I assume it only happens after generating a higher amount of captchas.

**Comment by Korkman** [comment]
As I read it, threadDelay = 2 and throttle = 1000 means every 2 seconds the BackgroundTask should fill the stock of prerendered captchas? Should be plenty for my use-case.

**Comment by hrj** [comment]
> As I read it, threadDelay = 2 and throttle = 1000 means every 2 seconds the BackgroundTask should fill the stock of prerendered captchas to 1000?

Yes, that's correct.

Another thing to note is that, the same CAPTCHA can be served multiple times. Only when you attempt a solution (successfully or not), does the CAPTCHA's attempt count increase. And when the attemptCount reaches a certain threshold (currently 10), the CAPTCHA is garbage collected, that is, not served anymore.

So what might be happening is, by a fluke of randomness, the number of RainDropsCaptcha challenges created in your current database might be so few that the same one gets served repeatedly. Unless you attempt some of them, there will be no garbage collection, and the same challenge will continue to be served.

In production, this should not be a problem, because when the CAPTCHAs are attempted, the churn will ensure that new challenges get created.

If you want to verify this in testing, try to solve the challenges whenever you see them. Doesn't have to be a correct solution. Even wrong attempts will eventually trigger garbage collection.

**Comment by Korkman** [comment]
Happens on master branch, too. This time immediately in the playground demo.

**Comment by hrj** [comment]
> Happens on master branch, too. This time immediately in the playground demo.

Interesting. Are you connecting to the same database? This will happen if you checked out the git repo in the same folder where you kept the v1.1 jar file.

Anyway, try attempting the challenge, to see if it gets replaced after 10 attempts.

**Comment by Korkman** [comment]
I just noticed the challenge is replaced every 10 clicks on "Get new captcha".

**Comment by Korkman** [comment]
Recreated the database on the master instance, now I get a different captcha on every click. Will test further.

**Comment by Korkman** [comment]
On master: After exhausting the pre-rendered captchas and then switching from 'easy' to 'medium', I am getting empty responses for the media query (resulting in broken pict in the playground demo). Doesn't seem to recover. Restarting the container fixed it.

**Comment by hrj** [comment]
> On master: After exhausting the pre-rendered captchas and then switching from 'easy' to 'medium', I am getting empty responses for the media query (resulting in broken pict in the playground demo). Doesn't seem to recover. Restarting the container fixed it.

If you see this bug again, can you create a separate issue, with instructions to reproduce it? Also, any errors / logs would be appreciated.

Best would be to create a bash / python script that repeatedly calls the endpoint with the exact parameters that you are querying with.

Also, share the config file, because it contains the random number seed and other configurations that we can use to reproduce the issue.

**Comment by hrj** [comment]
> This is bad. I can open 10 captcha protected actions, solve the captcha once and perform all 10 actions.

If it gets repeated in a predictable manner, then yes, it can be exploited. But, by design, the probability of that happening should be low. There might be some implementation bug however, which we need to test / review.

**Comment by Korkman** [comment]
@hrj I am able to reproduce now. Opening a new issue as requested.
