### ISSUE TITLE
Error in LabelCaptcha during validation

### ISSUE THREAD

**Issue by rr83019** [librecaptcha/lc-core#40]
The `/answer` endpoint has been throwing the following error whenever invoked, after the running the performance tests
`Error processing request: key not found: 4874`

**Comment by hrj** [comment]
The problem is specific to LabelCaptcha. Will investigate.

**Comment by hrj** [comment]
Fixed in 245521017adf7dc9df42ee08163c8a8e40aedce8

The problem was that LabelCaptcha didn't store any state in the token. Hence, after a restart of the server the token couldn't be used to verify a captcha response.

I have done a quick fix, by storing the file-names in the token. It is okay for the POC, because the framework remaps the raw tokens to an opaque token anyway.
